
import './globals.css'
import { Inter } from 'next/font/google'
import AuthProviders from './components/AuthProviders';
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className='relative'>
                <AuthProviders>
                    <Navbar />
                    <main className='bg-bg-main'>
                        <div className=' mx-auto min-h-screen bg-background-main'>
                            {children}
                        </div>
                    </main>
                    <Footer />
                </AuthProviders>
            </body>
        </html>
    )
}
